services:
    crafty:
        container_name: crafty_container
        image: registry.gitlab.com/crafty-controller/crafty-4:4.10.7
        restart: always
        environment:
            - TZ=America/Los_Angeles
        ports:
            - "8443:8443" # HTTPS
        volumes:
            - /home/core/docker/crafty-4/backups:/crafty/backups
            - /home/core/docker/crafty-4/logs:/crafty/logs
            - /home/core/docker/crafty-4/servers:/crafty/servers
            - /home/core/docker/crafty-4/config:/crafty/app/config
            - /home/core/docker/crafty-4/import:/crafty/import
